# Generated by Django 4.2 on 2023-06-19 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CarPool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riderequest',
            name='dID',
        ),
        migrations.RemoveField(
            model_name='riderequest',
            name='pID',
        ),
        migrations.RemoveField(
            model_name='riderequest',
            name='rID',
        ),
        migrations.RemoveField(
            model_name='riderequest',
            name='vID',
        ),
        migrations.DeleteModel(
            name='Driver',
        ),
        migrations.DeleteModel(
            name='Passenger',
        ),
        migrations.DeleteModel(
            name='RideRequest',
        ),
        migrations.DeleteModel(
            name='Routes',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
