# Generated by Django 4.2 on 2023-06-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarPool', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='pID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
