# Generated by Django 4.2 on 2023-06-19 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('CarPool', '0005_remove_riderequest_did_remove_riderequest_pid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('dID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('studentID', models.CharField(max_length=11)),
                ('dName', models.TextField(max_length=128)),
                ('dPhone', models.CharField(max_length=11)),
                ('plate', models.CharField(max_length=7)),
                ('carcolor', models.TextField(max_length=128)),
                ('dPass', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('pID', models.AutoField(primary_key=True, serialize=False)),
                ('pName', models.TextField(max_length=128)),
                ('pPhone', models.CharField(max_length=11)),
                ('studentID', models.CharField(max_length=11)),
                ('pPass', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('rID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('rTo', models.TextField(max_length=128)),
                ('rFrom', models.TextField(max_length=128)),
                ('rPrice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vID', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('CarModel', models.TextField(max_length=128)),
                ('CarType', models.TextField(max_length=128)),
                ('capacity', models.IntegerField()),
                ('brand', models.TextField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='RideRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField()),
                ('status', models.CharField(max_length=128)),
                ('dID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPool.driver')),
                ('pID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPool.passenger')),
                ('rID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPool.routes')),
                ('vID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPool.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='vID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarPool.vehicle'),
        ),
    ]
