# Generated by Django 4.2 on 2023-06-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarPool', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='dID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='routes',
            name='rID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
