# Generated by Django 4.2 on 2023-06-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarPool', '0008_alter_riderequest_did_alter_riderequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='passengers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
