# Generated by Django 4.2.3 on 2023-08-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarPool', '0009_riderequest_passengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='status',
            field=models.CharField(default='Pending', max_length=128),
        ),
    ]
