# Generated by Django 4.2.3 on 2023-08-11 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CarPool', '0010_alter_riderequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='dID',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='CarPool.driver'),
        ),
        migrations.AlterField(
            model_name='riderequest',
            name='vID',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='CarPool.vehicle'),
        ),
    ]
