# Generated by Django 4.2.3 on 2023-08-14 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarPool', '0011_alter_riderequest_did_alter_riderequest_vid'),
    ]

    operations = [
        migrations.AddField(
            model_name='riderequest',
            name='payment',
            field=models.TextField(default='Cash', max_length=128),
        ),
    ]
