# Generated by Django 4.2.3 on 2023-08-14 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarPool', '0012_riderequest_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riderequest',
            name='payment',
            field=models.CharField(default='Cash', max_length=128),
        ),
    ]
